### ISSUE TITLE
Metrics reporting is broken for Pipeline Jobs

### ISSUE THREAD

**Issue by exuperok** [DataDog/jenkins-datadog-plugin#71] opened 2016-12-09 15:58 UTC
Hello,

It seems that for jenkins2.x piepline jobs and multibranch piepline jobs (including github organisation) only job started event is reported. The job.juration and job.completed metrics are not reported at all.

Is there a possible fix to these issues as they both have the effect of rendering jenkins integration quite irrelevant, since there's no metric to report?

Thanks in advance.

**Comment by jalessio** [comment] 2017-02-16 22:24
This appears to be a duplicate of #51 

The following PR's aim to fix this:
* "Fix duration of pipeline jobs" #70
* "Jenkins pipeline support" #69

I cannot comment on the validity of any of them -- I'm just connecting the dots here since I'd like to use this feature.

**Comment by sjenriquez** [comment] 2017-04-12 18:19
Support will go out with our next release.

**Closed by sjenriquez** 2017-04-12 18:19 UTC
