### ISSUE TITLE
Support for Jenkins2 Pipeline

### ISSUE THREAD

**Issue by kitamurakei** [DataDog/jenkins-datadog-plugin#51] opened 2016-08-01 04:28 UTC
In Jenkins2 Pipeline, Datadog Event Monitor is unstable work.
Maybe cause, in Jenkins2 Pipeline, [run.getDuration()](https://github.com/DataDog/jenkins-datadog-plugin/blob/master/src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java#L211) is always return 0.

**Comment by jalessio** [comment] 2017-02-16 22:25
This appears to be a duplicate of #71 

The following PR's aim to fix this:
* "Fix duration of pipeline jobs" #70
* "Jenkins pipeline support" #69

I cannot comment on the validity of any of them -- I'm just connecting the dots here since I'd like to use this feature.

**Closed** 2017-04-11 17:35 UTC
